---
version: '3.8'

services:
  elm:
    build:
      context: .
    container_name: elm
    hostname: elm
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${PWD}/app/
        target: /var/local/app/
