---
version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${PWD}/app/
        target: /usr/share/nginx/html/
