---
version: '3.8'

services:
  elm:
    #image: codesimple/elm:0.19
    build: .
    container_name: elm
    hostname: elm
    entrypoint: ''
    working_dir: /var/local/app/
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ${PWD}/elm-architecture-tutorial/
        target: /var/local/app/
