---
version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${PWD}/dist/
        target: /usr/share/nginx/html/
  elm:
    image: sunakan/elm:0.19.1
    container_name: elm
    hostname: elm
    working_dir: /usr/share/elm/
    volumes:
      - type: bind
        source: ${PWD}/
        target: /usr/share/elm/
